S6-DjangoTemplates/django_project/django_app/urls.py
from django.urls import path
from django_app import views

# TEMPLATE TAGGING
app_name = 'django_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('help/', views.help, name='help'),
    path('relative/', views.relative, name='relative'),
]

S6-DjangoTemplates/django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django_app.urls')),
]

S6-DjangoTemplates/django_project/django_app/models.py
from django.db import models

# Create your models here.

S6-DjangoTemplates/django_project/django_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context = {'text': 'Hello world', 'number': 100}
    return render(request, 'index.html', context)


def help(request):
    return render(request, 'help.html')


def relative(request):
    return render(request, 'relative_url_templates.html')

S6-DjangoTemplates/django_project/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8" />
    <title>Django App</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
  </head>
  <body>
    <nav class="navbar">
      <a href="{% url 'django_app:index' %}" class="nav__navLogo">
        <img src="{% static 'images/django-logo.png' %}" alt="django-logo" />
      </a>
      <ul class="nav__navList">
        <li class="nav__navItem">
          <a href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav__navItem">
          <a href="{% url 'django_app:help' %}">Help</a>
        </li>
      </ul>
    </nav>
    <div class="container">{% block body_block %} {% endblock %}</div>
  </body>
</html>

S6-DjangoTemplates/django_project/templates/help.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load staticfiles %} {% block body_block%}
<h1>This is Help Page</h1>

<link rel="stylesheet" type="text/css" href="{% static 'css/help.css' %}" />
{% endblock %}

S6-DjangoTemplates/django_project/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %} {% load staticfiles %} {% block body_block %}
<h1>Hello welcome to Django App</h1>
<h3>{{ text|cut:"Hel"|upper }}</h3>
<h3>{{ number|add:'1' }}</h3>
{% endblock body_block %}

S6-DjangoTemplates/django_project/templates/relative_url_templates.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8" />
    <title>Django App</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/relative_url_templates.css' %}"
    />
  </head>
  <body>
    <h1>This is Relative URL Templates</h1>
    <a href="{% url 'django_app:help' %}">This will lead to Help Page</a>
    <a href="{% url 'admin:index' %}">This will lead to Admin Page</a>
    {% comment %}
    <a href="{% url 'index' %}">This will lead to Home Page</a>
    {% endcomment %}
  </body>
</html>