S7-DjangoAuth/django_project/django_app/urls.py
from django.urls import path
from django_app import views

app_name = 'django_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

S7-DjangoAuth/django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django_app.urls')),
]

S7-DjangoAuth/django_project/django_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete='CASCADE')

    # Additional attributes
    portofolio_site = models.URLField(blank=True)
    profile_pict = models.ImageField(upload_to='profile_picts', blank=True)

    def __str__(self):
        return self.user.username

S7-DjangoAuth/django_project/django_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ['username', 'email', 'password']


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ['portofolio_site', 'profile_pict']


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=255)
    password = forms.CharField(widget=forms.PasswordInput, max_length=255)

    def __str__(self):
        return self.username

S7-DjangoAuth/django_project/django_app/views.py
from django.shortcuts import render
from django_app.forms import UserForm, UserProfileInfoForm, UserLoginForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    return render(request, 'index.html')


def register(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        user_profile_form = UserProfileInfoForm(request.POST)

        if user_form.is_valid() and user_profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_profile = user_profile_form.save(commit=False)
            user_profile.user = user

            if 'profile_pict' in request.FILES:
                user_profile.profile_pict = request.FILES['profile_pict']

            user_profile.save()

            registered = True

        else:
            print(user_form.errors, user_profile_form.errors)
            registered = False

    else:
        user_form = UserForm()
        user_profile_form = UserProfileInfoForm()
        registered = False

    context = {
        'registered': registered,
        'user_form': user_form,
        'user_profile_form': user_profile_form
    }

    return render(request, 'registration.html', context)


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('django_app:index'))

                else:
                    return HttpResponse('ACCOUNT NOT ACTIVE!')
            else:
                print('Someone tried to login and failed!')
                print('username: {}, password: {}'.format(username, password))
                return HttpResponse('INVALID LOGIN DETAILS SUPPLIED!')

    else:
        form = UserLoginForm()
        context = {'form': form}
        return render(request, 'login.html', context)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('django_app:index'))


@login_required
def special(request):
    return HttpResponse('YOU ARE LOGGED IN, NICE!')

S7-DjangoAuth/django_project/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
  </head>
  <body>
    <header class="base__header">
      <nav class="base__nav container">
        <a class="nav__navLogo" href="{% url 'django_app:index' %}">
          <img src="{% static 'images/django-logo.png' %}" alt="django logo" />
        </a>
        <ul class="nav__navList">
          <li class="nav__navItem">
            <a href="{% url 'django_app:register' %}">Register</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav__navItem">
            <a href="{% url 'django_app:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav__navItem">
            <a href="{% url 'django_app:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <div class="base__body container">
      {% block body_block %} {% endblock body_block %}
    </div>
  </body>
</html>

S7-DjangoAuth/django_project/templates/index.html
{% extends 'base.html' %} {% load staticfiles %} {% block body_block %}
<div class="home">
  {% if user.is_authenticated %}
  <h1>Welcome {{ user.username }}</h1>
  {% else %}
  <h1>This is Home Page of Django App</h1>
  {% endif %}
</div>
<link rel="stylesheet" href="{% static 'css/index.css' %}" />
{% endblock body_block %}

S7-DjangoAuth/django_project/templates/login.html
{% extends 'base.html' %} {% load staticfiles %} {% block body_block %}
<div class="registration">
  <h1>This is Login Page of Django App</h1>
  <form
    method="POST"
    enctype="multipart/form-data"
    class="register__form"
    action="{% url 'django_app:login' %}"
  >
    {% csrf_token %} {% for field in form %}
    <div class="form__formControl">
      {{ field.errors }} {{ field.label_tag }} {{ field }}
    </div>
    {% endfor %}
    <div class="form__buttonControl">
      <input type="submit" value="Login" />
    </div>
  </form>
</div>
<link rel="stylesheet" href="{% static 'css/registration.css' %}" />
{% endblock body_block %}

S7-DjangoAuth/django_project/templates/registration.html
{% extends 'base.html' %} {% load staticfiles %} {% block body_block %}
<div class="registration">
  <h1>This is Register Page of Django App</h1>
  <form
    method="POST"
    enctype="multipart/form-data"
    class="register__form"
    action="{% url 'django_app:register' %}"
  >
    {% csrf_token %} {% for field in user_form %}
    <div class="form__formControl">
      {{ field.errors }} {{ field.label_tag }} {{ field }}
    </div>
    {% endfor %} {% for field in user_profile_form %}
    <div class="form__formControl">
      {{ field.errors }} {{ field.label_tag }} {{ field }}
    </div>
    {% endfor %}
    <div class="form__buttonControl">
      <input type="submit" value="Submit" />
    </div>
  </form>
</div>
<link rel="stylesheet" href="{% static 'css/registration.css' %}" />
{% endblock body_block %}